2025-03-17 19:57:24,954 INFO    MainThread:32875 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_setup.py:_flush():67] Configure stats pid to 32875
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_setup.py:_flush():67] Loading settings from /Users/jaebincheong/.config/wandb/settings
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_setup.py:_flush():67] Loading settings from /Users/jaebincheong/YBIGTA/25-1_sessions/Week1/25-1-DS-Week-1-Assignment/wandb/settings
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/jaebincheong/YBIGTA/25-1_sessions/Week1/25-1-DS-Week-1-Assignment/wandb/run-20250317_195724-iqqfep0p/logs/debug.log
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/jaebincheong/YBIGTA/25-1_sessions/Week1/25-1-DS-Week-1-Assignment/wandb/run-20250317_195724-iqqfep0p/logs/debug-internal.log
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x16a954c20>
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:init():761] calling init triggers
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'src_vocab_size': 100, 'tgt_vocab_size': 200, 'd_model': 32, 'n_heads': 4, 'd_ff': 64, 'num_encoder_layers': 6, 'num_decoder_layers': 6, 'dropout': 0.1, 'batch_size': 32, 'num_epochs': 50, 'learning_rate': 0.0001, '_wandb': {}}
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:init():784] starting backend
2025-03-17 19:57:24,955 INFO    MainThread:32875 [wandb_init.py:init():788] sending inform_init request
2025-03-17 19:57:24,975 INFO    MainThread:32875 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-17 19:57:24,975 INFO    MainThread:32875 [wandb_init.py:init():798] backend started and connected
2025-03-17 19:57:24,979 INFO    MainThread:32875 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-17 19:57:24,980 INFO    MainThread:32875 [wandb_init.py:init():891] updated telemetry
2025-03-17 19:57:24,999 INFO    MainThread:32875 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-17 19:57:25,416 INFO    MainThread:32875 [wandb_init.py:init():990] starting run threads in backend
2025-03-17 19:57:25,632 INFO    MainThread:32875 [wandb_run.py:_console_start():2375] atexit reg
2025-03-17 19:57:25,633 INFO    MainThread:32875 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-17 19:57:25,633 INFO    MainThread:32875 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-17 19:57:25,633 INFO    MainThread:32875 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-17 19:57:25,634 INFO    MainThread:32875 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-17 19:57:57,799 INFO    MainThread:32875 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-17 19:57:57,800 INFO    MainThread:32875 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-17 19:58:17,231 WARNING MsgRouterThr:32875 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-17 19:58:17,233 INFO    MsgRouterThr:32875 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
